// Code generated by tgpiler. DO NOT EDIT.
// Source: proto definitions + stored procedures

package cart

import (
	"context"
	"database/sql"
	"fmt"
)

// ============================================================================
// CartService Repository Implementation
// ============================================================================

// CartServiceRepository defines the data access interface for CartService.
type CartServiceRepository interface {
	GetCart(ctx context.Context, req *GetCartRequest) (*GetCartResponse, error)
	AddToCart(ctx context.Context, req *AddToCartRequest) (*AddToCartResponse, error)
	UpdateCartItem(ctx context.Context, req *UpdateCartItemRequest) (*UpdateCartItemResponse, error)
	RemoveFromCart(ctx context.Context, req *RemoveFromCartRequest) (*RemoveFromCartResponse, error)
	ClearCart(ctx context.Context, req *ClearCartRequest) (*ClearCartResponse, error)
	ValidateCart(ctx context.Context, req *ValidateCartRequest) (*ValidateCartResponse, error)
}

// CartServiceRepositorySQL implements CartServiceRepository using stored procedures.
type CartServiceRepositorySQL struct {
	db *sql.DB
}

// NewCartServiceRepositorySQL creates a new SQL repository.
func NewCartServiceRepositorySQL(db *sql.DB) *CartServiceRepositorySQL {
	return &CartServiceRepositorySQL{db: db}
}


// GetCart implements the GetCart operation.
// Mapped to: usp_GetCart (confidence: 100%, exact match: usp_GetCart)
func (r *CartServiceRepositorySQL) GetCart(ctx context.Context, req *GetCartRequest) (*GetCartResponse, error) {
	// Execute stored procedure and scan results
	query := "EXEC usp_GetCart @UserId"
	row := r.db.QueryRowContext(ctx, query, req.UserID)
	
	var result CartResponse
	err := row.Scan()
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("GetCart: not found")
		}
		return nil, fmt.Errorf("GetCart: %w", err)
	}
	
	return &GetCartResponse{
		CartResponse: &result,
	}, nil
}


// AddToCart implements the AddToCart operation.
// Mapped to: usp_AddToCart (confidence: 100%, exact match: usp_AddToCart)
func (r *CartServiceRepositorySQL) AddToCart(ctx context.Context, req *AddToCartRequest) (*AddToCartResponse, error) {
	// Execute stored procedure and scan results
	query := "EXEC usp_AddToCart @UserId, @ProductId, @Quantity"
	row := r.db.QueryRowContext(ctx, query, req.UserID, req.ProductID, req.Quantity)
	
	var result AddToCartResponse
	err := row.Scan()
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("AddToCart: not found")
		}
		return nil, fmt.Errorf("AddToCart: %w", err)
	}
	
	return &AddToCartResponse{
	}, nil
}


// UpdateCartItem implements the UpdateCartItem operation.
// Mapped to: usp_UpdateCartItem (confidence: 100%, exact match: usp_UpdateCartItem)
func (r *CartServiceRepositorySQL) UpdateCartItem(ctx context.Context, req *UpdateCartItemRequest) (*UpdateCartItemResponse, error) {
	// Execute stored procedure (no result mapping)
	query := "EXEC usp_UpdateCartItem @UserId, @ProductId, @Quantity"
	_, err := r.db.ExecContext(ctx, query, req.UserID, req.ProductID, req.Quantity)
	if err != nil {
		return nil, fmt.Errorf("UpdateCartItem: %w", err)
	}
	
	return &UpdateCartItemResponse{}, nil
}


// RemoveFromCart implements the RemoveFromCart operation.
// Mapped to: usp_RemoveFromCart (confidence: 100%, exact match: usp_RemoveFromCart)
func (r *CartServiceRepositorySQL) RemoveFromCart(ctx context.Context, req *RemoveFromCartRequest) (*RemoveFromCartResponse, error) {
	// Execute stored procedure (no result mapping)
	query := "EXEC usp_RemoveFromCart @UserId, @ProductId"
	_, err := r.db.ExecContext(ctx, query, req.UserID, req.ProductID)
	if err != nil {
		return nil, fmt.Errorf("RemoveFromCart: %w", err)
	}
	
	return &RemoveFromCartResponse{}, nil
}


// ClearCart implements the ClearCart operation.
// Mapped to: usp_ClearCart (confidence: 100%, exact match: usp_ClearCart)
func (r *CartServiceRepositorySQL) ClearCart(ctx context.Context, req *ClearCartRequest) (*ClearCartResponse, error) {
	// Execute stored procedure (no result mapping)
	query := "EXEC usp_ClearCart @UserId"
	_, err := r.db.ExecContext(ctx, query, req.UserID)
	if err != nil {
		return nil, fmt.Errorf("ClearCart: %w", err)
	}
	
	return &ClearCartResponse{}, nil
}


// ValidateCart implements the ValidateCart operation.
// Mapped to: usp_ValidateCart (confidence: 100%, exact match: usp_ValidateCart)
func (r *CartServiceRepositorySQL) ValidateCart(ctx context.Context, req *ValidateCartRequest) (*ValidateCartResponse, error) {
	// Execute stored procedure (no result mapping)
	query := "EXEC usp_ValidateCart @UserId"
	_, err := r.db.ExecContext(ctx, query, req.UserID)
	if err != nil {
		return nil, fmt.Errorf("ValidateCart: %w", err)
	}
	
	return &ValidateCartResponse{}, nil
}


// ============================================================================
// CartService Server
// ============================================================================

// CartServiceServer implements the CartService gRPC service.
type CartServiceServer struct {
	repo CartServiceRepository
}

// NewCartServiceServer creates a new server.
func NewCartServiceServer(repo CartServiceRepository) *CartServiceServer {
	return &CartServiceServer{repo: repo}
}


// GetCart handles the GetCart RPC.
func (s *CartServiceServer) GetCart(ctx context.Context, req *GetCartRequest) (*GetCartResponse, error) {
	return s.repo.GetCart(ctx, req)
}

// AddToCart handles the AddToCart RPC.
func (s *CartServiceServer) AddToCart(ctx context.Context, req *AddToCartRequest) (*AddToCartResponse, error) {
	return s.repo.AddToCart(ctx, req)
}

// UpdateCartItem handles the UpdateCartItem RPC.
func (s *CartServiceServer) UpdateCartItem(ctx context.Context, req *UpdateCartItemRequest) (*UpdateCartItemResponse, error) {
	return s.repo.UpdateCartItem(ctx, req)
}

// RemoveFromCart handles the RemoveFromCart RPC.
func (s *CartServiceServer) RemoveFromCart(ctx context.Context, req *RemoveFromCartRequest) (*RemoveFromCartResponse, error) {
	return s.repo.RemoveFromCart(ctx, req)
}

// ClearCart handles the ClearCart RPC.
func (s *CartServiceServer) ClearCart(ctx context.Context, req *ClearCartRequest) (*ClearCartResponse, error) {
	return s.repo.ClearCart(ctx, req)
}

// ValidateCart handles the ValidateCart RPC.
func (s *CartServiceServer) ValidateCart(ctx context.Context, req *ValidateCartRequest) (*ValidateCartResponse, error) {
	return s.repo.ValidateCart(ctx, req)
}

