// Code generated by tgpiler. DO NOT EDIT.
// Source: proto definitions + stored procedures

package catalog

import (
	"context"
	"database/sql"
	"fmt"
	"time"
)

// ============================================================================
// CatalogService Repository Implementation
// ============================================================================

// CatalogServiceRepository defines the data access interface for CatalogService.
type CatalogServiceRepository interface {
	GetCategory(ctx context.Context, req *GetCategoryRequest) (*GetCategoryResponse, error)
	GetCategoryBySlug(ctx context.Context, req *GetCategoryBySlugRequest) (*GetCategoryBySlugResponse, error)
	ListCategories(ctx context.Context, req *ListCategoriesRequest) (*ListCategoriesResponse, error)
	CreateCategory(ctx context.Context, req *CreateCategoryRequest) (*CreateCategoryResponse, error)
	UpdateCategory(ctx context.Context, req *UpdateCategoryRequest) (*UpdateCategoryResponse, error)
	GetProduct(ctx context.Context, req *GetProductRequest) (*GetProductResponse, error)
	GetProductBySku(ctx context.Context, req *GetProductBySkuRequest) (*GetProductBySkuResponse, error)
	GetProductBySlug(ctx context.Context, req *GetProductBySlugRequest) (*GetProductBySlugResponse, error)
	ListProducts(ctx context.Context, req *ListProductsRequest) (*ListProductsResponse, error)
	CreateProduct(ctx context.Context, req *CreateProductRequest) (*CreateProductResponse, error)
	UpdateProduct(ctx context.Context, req *UpdateProductRequest) (*UpdateProductResponse, error)
	DeleteProduct(ctx context.Context, req *DeleteProductRequest) (*DeleteProductResponse, error)
	SearchProducts(ctx context.Context, req *SearchProductsRequest) (*SearchProductsResponse, error)
}

// CatalogServiceRepositorySQL implements CatalogServiceRepository using stored procedures.
type CatalogServiceRepositorySQL struct {
	db *sql.DB
}

// NewCatalogServiceRepositorySQL creates a new SQL repository.
func NewCatalogServiceRepositorySQL(db *sql.DB) *CatalogServiceRepositorySQL {
	return &CatalogServiceRepositorySQL{db: db}
}


// GetCategory implements the GetCategory operation.
// Mapped to: usp_GetCategoryById (confidence: 95%, get by id pattern)
func (r *CatalogServiceRepositorySQL) GetCategory(ctx context.Context, req *GetCategoryRequest) (*GetCategoryResponse, error) {
	// Execute stored procedure and scan results
	query := "EXEC usp_GetCategoryById @CategoryId"
	row := r.db.QueryRowContext(ctx, query, req.ID)
	var nested Category
	err := row.Scan(&nested.ID, &nested.Name, &nested.Slug, &nested.Description, &nested.ParentID, &nested.DisplayOrder, &nested.IsActive, &nested.ImageURL, &nested.CreatedAt)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("GetCategory: not found")
		}
		return nil, fmt.Errorf("GetCategory: %w", err)
	}
	
	return &GetCategoryResponse{
		Category: &nested,
	}, nil
}


// GetCategoryBySlug implements the GetCategoryBySlug operation.
// Mapped to: usp_GetCategoryBySlug (confidence: 100%, exact match: usp_GetCategoryBySlug)
func (r *CatalogServiceRepositorySQL) GetCategoryBySlug(ctx context.Context, req *GetCategoryBySlugRequest) (*GetCategoryBySlugResponse, error) {
	// Execute stored procedure and scan results
	query := "EXEC usp_GetCategoryBySlug @Slug"
	row := r.db.QueryRowContext(ctx, query, req.Slug)
	var nested Category
	err := row.Scan(&nested.ID, &nested.Name, &nested.Slug, &nested.Description, &nested.ParentID, &nested.DisplayOrder, &nested.IsActive, &nested.ImageURL, &nested.CreatedAt)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("GetCategoryBySlug: not found")
		}
		return nil, fmt.Errorf("GetCategoryBySlug: %w", err)
	}
	
	return &GetCategoryBySlugResponse{
		Category: &nested,
	}, nil
}


// ListCategories implements the ListCategories operation.
// Mapped to: usp_ListCategories (confidence: 75%, exact match: usp_ListCategories)
func (r *CatalogServiceRepositorySQL) ListCategories(ctx context.Context, req *ListCategoriesRequest) (*ListCategoriesResponse, error) {
	// Execute stored procedure and scan results
	query := "EXEC usp_ListCategories @ParentId, @IncludeInactive"
	row := r.db.QueryRowContext(ctx, query, req.ParentID, req.IncludeInactive)
	var nested Category
	err := row.Scan(&nested.ID, &nested.Name, &nested.Slug, &nested.Description, &nested.ParentID, &nested.DisplayOrder, &nested.IsActive, &nested.ImageURL, &nested.CreatedAt)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("ListCategories: not found")
		}
		return nil, fmt.Errorf("ListCategories: %w", err)
	}
	
	return &ListCategoriesResponse{
		Categories: &nested,
	}, nil
}


// CreateCategory implements the CreateCategory operation.
// Mapped to: usp_CreateCategory (confidence: 100%, exact match: usp_CreateCategory)
func (r *CatalogServiceRepositorySQL) CreateCategory(ctx context.Context, req *CreateCategoryRequest) (*CreateCategoryResponse, error) {
	// Execute stored procedure and scan results
	query := "EXEC usp_CreateCategory @Name, @Slug, @Description, @ParentId, @DisplayOrder, @ImageUrl"
	row := r.db.QueryRowContext(ctx, query, req.Name, req.Slug, req.Description, req.ParentID, req.DisplayOrder, req.ImageURL)
	var nested Category
	err := row.Scan(&nested.ID, &nested.Name, &nested.Slug, &nested.Description, &nested.ParentID, &nested.DisplayOrder, &nested.IsActive, &nested.ImageURL, &nested.CreatedAt)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("CreateCategory: not found")
		}
		return nil, fmt.Errorf("CreateCategory: %w", err)
	}
	
	return &CreateCategoryResponse{
		Category: &nested,
	}, nil
}


// UpdateCategory implements the UpdateCategory operation.
// Mapped to: usp_UpdateCategory (confidence: 100%, exact match: usp_UpdateCategory)
func (r *CatalogServiceRepositorySQL) UpdateCategory(ctx context.Context, req *UpdateCategoryRequest) (*UpdateCategoryResponse, error) {
	// Execute stored procedure and scan results
	query := "EXEC usp_UpdateCategory @CategoryId, @Name, @Description, @DisplayOrder, @IsActive, @ImageUrl"
	row := r.db.QueryRowContext(ctx, query, req.ID, req.Name, req.Description, req.DisplayOrder, req.IsActive, req.ImageURL)
	var nested Category
	err := row.Scan(&nested.ID, &nested.Name, &nested.Slug, &nested.Description, &nested.ParentID, &nested.DisplayOrder, &nested.IsActive, &nested.ImageURL, &nested.CreatedAt)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("UpdateCategory: not found")
		}
		return nil, fmt.Errorf("UpdateCategory: %w", err)
	}
	
	return &UpdateCategoryResponse{
		Category: &nested,
	}, nil
}


// GetProduct implements the GetProduct operation.
// Mapped to: usp_GetProductById (confidence: 95%, get by id pattern)
func (r *CatalogServiceRepositorySQL) GetProduct(ctx context.Context, req *GetProductRequest) (*GetProductResponse, error) {
	// Execute stored procedure and scan results
	query := "EXEC usp_GetProductById @ProductId"
	row := r.db.QueryRowContext(ctx, query, req.ID)
	var nested Product
	err := row.Scan()
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("GetProduct: not found")
		}
		return nil, fmt.Errorf("GetProduct: %w", err)
	}
	
	return &GetProductResponse{
		Product: &nested,
	}, nil
}


// GetProductBySku implements the GetProductBySku operation.
// Mapped to: usp_GetProductBySku (confidence: 100%, exact match: usp_GetProductBySku)
func (r *CatalogServiceRepositorySQL) GetProductBySku(ctx context.Context, req *GetProductBySkuRequest) (*GetProductBySkuResponse, error) {
	// Execute stored procedure (no result mapping)
	query := "EXEC usp_GetProductBySku @Sku"
	_, err := r.db.ExecContext(ctx, query, req.SKU)
	if err != nil {
		return nil, fmt.Errorf("GetProductBySku: %w", err)
	}
	
	return &GetProductBySkuResponse{}, nil
}


// GetProductBySlug implements the GetProductBySlug operation.
// Mapped to: usp_GetProductBySlug (confidence: 100%, exact match: usp_GetProductBySlug)
func (r *CatalogServiceRepositorySQL) GetProductBySlug(ctx context.Context, req *GetProductBySlugRequest) (*GetProductBySlugResponse, error) {
	// Execute stored procedure (no result mapping)
	query := "EXEC usp_GetProductBySlug @Slug"
	_, err := r.db.ExecContext(ctx, query, req.Slug)
	if err != nil {
		return nil, fmt.Errorf("GetProductBySlug: %w", err)
	}
	
	return &GetProductBySlugResponse{}, nil
}


// ListProducts implements the ListProducts operation.
// Mapped to: usp_ListProducts (confidence: 75%, exact match: usp_ListProducts)
func (r *CatalogServiceRepositorySQL) ListProducts(ctx context.Context, req *ListProductsRequest) (*ListProductsResponse, error) {
	// Execute stored procedure and scan results
	query := "EXEC usp_ListProducts @CategoryId, @SearchQuery, @InStockOnly, @IncludeInactive, @SortBy, @SortDescending"
	row := r.db.QueryRowContext(ctx, query, req.CategoryID, req.SearchQuery, req.InStockOnly, req.IncludeInactive, req.SortBy, req.SortDescending)
	var result ListProductsResponse
	err := row.Scan()
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("ListProducts: not found")
		}
		return nil, fmt.Errorf("ListProducts: %w", err)
	}
	
	return &result, nil
}


// CreateProduct implements the CreateProduct operation.
// Mapped to: usp_CreateProduct (confidence: 90%, exact match: usp_CreateProduct)
func (r *CatalogServiceRepositorySQL) CreateProduct(ctx context.Context, req *CreateProductRequest) (*CreateProductResponse, error) {
	// Execute stored procedure (no result mapping)
	query := "EXEC usp_CreateProduct @Sku, @Name, @Slug, @Description, @PriceUnits, @CategoryId, @TrackInventory, @InitialStock"
	_, err := r.db.ExecContext(ctx, query, req.SKU, req.Name, req.Slug, req.Description, nil, req.CategoryID, req.TrackInventory, req.InitialStock)
	if err != nil {
		return nil, fmt.Errorf("CreateProduct: %w", err)
	}
	
	return &CreateProductResponse{}, nil
}


// UpdateProduct implements the UpdateProduct operation.
// Mapped to: usp_UpdateProduct (confidence: 100%, exact match: usp_UpdateProduct)
func (r *CatalogServiceRepositorySQL) UpdateProduct(ctx context.Context, req *UpdateProductRequest) (*UpdateProductResponse, error) {
	// Execute stored procedure (no result mapping)
	query := "EXEC usp_UpdateProduct @ProductId, @Name, @Description, @CategoryId, @IsActive"
	_, err := r.db.ExecContext(ctx, query, req.ID, req.Name, req.Description, req.CategoryID, req.IsActive)
	if err != nil {
		return nil, fmt.Errorf("UpdateProduct: %w", err)
	}
	
	return &UpdateProductResponse{}, nil
}


// DeleteProduct implements the DeleteProduct operation.
// Mapped to: usp_DeleteProduct (confidence: 100%, exact match: usp_DeleteProduct)
func (r *CatalogServiceRepositorySQL) DeleteProduct(ctx context.Context, req *DeleteProductRequest) (*DeleteProductResponse, error) {
	// Execute stored procedure and scan results
	query := "EXEC usp_DeleteProduct @ProductId"
	row := r.db.QueryRowContext(ctx, query, req.ID)
	var result DeleteProductResponse
	err := row.Scan(&result.Success)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("DeleteProduct: not found")
		}
		return nil, fmt.Errorf("DeleteProduct: %w", err)
	}
	
	return &result, nil
}


// SearchProducts implements the SearchProducts operation.
// Mapped to: usp_SearchProducts (confidence: 100%, exact match: usp_SearchProducts)
func (r *CatalogServiceRepositorySQL) SearchProducts(ctx context.Context, req *SearchProductsRequest) (*SearchProductsResponse, error) {
	// Execute stored procedure and scan results
	query := "EXEC usp_SearchProducts @Query, @CategoryIds"
	row := r.db.QueryRowContext(ctx, query, req.Query, req.CategoryIDs)
	var result SearchProductsResponse
	err := row.Scan()
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("SearchProducts: not found")
		}
		return nil, fmt.Errorf("SearchProducts: %w", err)
	}
	
	return &result, nil
}


// ============================================================================
// CatalogService Server
// ============================================================================

// CatalogServiceServer implements the CatalogService gRPC service.
type CatalogServiceServer struct {
	repo CatalogServiceRepository
}

// NewCatalogServiceServer creates a new server.
func NewCatalogServiceServer(repo CatalogServiceRepository) *CatalogServiceServer {
	return &CatalogServiceServer{repo: repo}
}


// GetCategory handles the GetCategory RPC.
func (s *CatalogServiceServer) GetCategory(ctx context.Context, req *GetCategoryRequest) (*GetCategoryResponse, error) {
	return s.repo.GetCategory(ctx, req)
}

// GetCategoryBySlug handles the GetCategoryBySlug RPC.
func (s *CatalogServiceServer) GetCategoryBySlug(ctx context.Context, req *GetCategoryBySlugRequest) (*GetCategoryBySlugResponse, error) {
	return s.repo.GetCategoryBySlug(ctx, req)
}

// ListCategories handles the ListCategories RPC.
func (s *CatalogServiceServer) ListCategories(ctx context.Context, req *ListCategoriesRequest) (*ListCategoriesResponse, error) {
	return s.repo.ListCategories(ctx, req)
}

// CreateCategory handles the CreateCategory RPC.
func (s *CatalogServiceServer) CreateCategory(ctx context.Context, req *CreateCategoryRequest) (*CreateCategoryResponse, error) {
	return s.repo.CreateCategory(ctx, req)
}

// UpdateCategory handles the UpdateCategory RPC.
func (s *CatalogServiceServer) UpdateCategory(ctx context.Context, req *UpdateCategoryRequest) (*UpdateCategoryResponse, error) {
	return s.repo.UpdateCategory(ctx, req)
}

// GetProduct handles the GetProduct RPC.
func (s *CatalogServiceServer) GetProduct(ctx context.Context, req *GetProductRequest) (*GetProductResponse, error) {
	return s.repo.GetProduct(ctx, req)
}

// GetProductBySku handles the GetProductBySku RPC.
func (s *CatalogServiceServer) GetProductBySku(ctx context.Context, req *GetProductBySkuRequest) (*GetProductBySkuResponse, error) {
	return s.repo.GetProductBySku(ctx, req)
}

// GetProductBySlug handles the GetProductBySlug RPC.
func (s *CatalogServiceServer) GetProductBySlug(ctx context.Context, req *GetProductBySlugRequest) (*GetProductBySlugResponse, error) {
	return s.repo.GetProductBySlug(ctx, req)
}

// ListProducts handles the ListProducts RPC.
func (s *CatalogServiceServer) ListProducts(ctx context.Context, req *ListProductsRequest) (*ListProductsResponse, error) {
	return s.repo.ListProducts(ctx, req)
}

// CreateProduct handles the CreateProduct RPC.
func (s *CatalogServiceServer) CreateProduct(ctx context.Context, req *CreateProductRequest) (*CreateProductResponse, error) {
	return s.repo.CreateProduct(ctx, req)
}

// UpdateProduct handles the UpdateProduct RPC.
func (s *CatalogServiceServer) UpdateProduct(ctx context.Context, req *UpdateProductRequest) (*UpdateProductResponse, error) {
	return s.repo.UpdateProduct(ctx, req)
}

// DeleteProduct handles the DeleteProduct RPC.
func (s *CatalogServiceServer) DeleteProduct(ctx context.Context, req *DeleteProductRequest) (*DeleteProductResponse, error) {
	return s.repo.DeleteProduct(ctx, req)
}

// SearchProducts handles the SearchProducts RPC.
func (s *CatalogServiceServer) SearchProducts(ctx context.Context, req *SearchProductsRequest) (*SearchProductsResponse, error) {
	return s.repo.SearchProducts(ctx, req)
}

