// Code generated by tgpiler. DO NOT EDIT.
// Source: proto definitions + stored procedures

package order

import (
	"context"
	"database/sql"
	"fmt"
	"time"
)

// ============================================================================
// OrderService Repository Implementation
// ============================================================================

// OrderServiceRepository defines the data access interface for OrderService.
type OrderServiceRepository interface {
	CreateOrder(ctx context.Context, req *CreateOrderRequest) (*CreateOrderResponse, error)
	GetOrder(ctx context.Context, req *GetOrderRequest) (*GetOrderResponse, error)
	GetOrderByNumber(ctx context.Context, req *GetOrderByNumberRequest) (*GetOrderByNumberResponse, error)
	ListOrders(ctx context.Context, req *ListOrdersRequest) (*ListOrdersResponse, error)
	UpdateOrderStatus(ctx context.Context, req *UpdateOrderStatusRequest) (*UpdateOrderStatusResponse, error)
	CancelOrder(ctx context.Context, req *CancelOrderRequest) (*CancelOrderResponse, error)
	ProcessPayment(ctx context.Context, req *ProcessPaymentRequest) (*ProcessPaymentResponse, error)
	RefundOrder(ctx context.Context, req *RefundOrderRequest) (*RefundOrderResponse, error)
	ValidateDiscountCode(ctx context.Context, req *ValidateDiscountCodeRequest) (*ValidateDiscountCodeResponse, error)
}

// OrderServiceRepositorySQL implements OrderServiceRepository using stored procedures.
type OrderServiceRepositorySQL struct {
	db *sql.DB
}

// NewOrderServiceRepositorySQL creates a new SQL repository.
func NewOrderServiceRepositorySQL(db *sql.DB) *OrderServiceRepositorySQL {
	return &OrderServiceRepositorySQL{db: db}
}


// CreateOrder implements the CreateOrder operation.
// Mapped to: usp_CreateOrder (confidence: 58%, exact match: usp_CreateOrder)
func (r *OrderServiceRepositorySQL) CreateOrder(ctx context.Context, req *CreateOrderRequest) (*CreateOrderResponse, error) {
	// Execute stored procedure and scan results
	query := "EXEC usp_CreateOrder @UserId, @ShippingAddressLine1, @ShippingCity, @ShippingState, @ShippingPostalCode, @ShippingCountry, @BillingAddressLine1, @BillingCity, @BillingState, @BillingPostalCode, @BillingCountry, @DiscountCode, @Notes, @PaymentMethodId"
	row := r.db.QueryRowContext(ctx, query, req.UserID, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, req.DiscountCode, req.Notes, req.PaymentMethodID)
	var result CreateOrderResponse
	err := row.Scan()
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("CreateOrder: not found")
		}
		return nil, fmt.Errorf("CreateOrder: %w", err)
	}
	
	return &result, nil
}


// GetOrder implements the GetOrder operation.
// Mapped to: usp_GetOrderById (confidence: 95%, get by id pattern)
func (r *OrderServiceRepositorySQL) GetOrder(ctx context.Context, req *GetOrderRequest) (*GetOrderResponse, error) {
	// Execute stored procedure and scan results
	query := "EXEC usp_GetOrderById @OrderId"
	row := r.db.QueryRowContext(ctx, query, req.ID)
	var nested Order
	err := row.Scan(&nested.ID)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("GetOrder: not found")
		}
		return nil, fmt.Errorf("GetOrder: %w", err)
	}
	
	return &GetOrderResponse{
		Order: &nested,
	}, nil
}


// GetOrderByNumber implements the GetOrderByNumber operation.
// Mapped to: usp_GetOrderByNumber (confidence: 100%, exact match: usp_GetOrderByNumber)
func (r *OrderServiceRepositorySQL) GetOrderByNumber(ctx context.Context, req *GetOrderByNumberRequest) (*GetOrderByNumberResponse, error) {
	// Execute stored procedure (no result mapping)
	query := "EXEC usp_GetOrderByNumber @OrderNumber"
	_, err := r.db.ExecContext(ctx, query, req.OrderNumber)
	if err != nil {
		return nil, fmt.Errorf("GetOrderByNumber: %w", err)
	}
	
	return &GetOrderByNumberResponse{}, nil
}


// ListOrders implements the ListOrders operation.
// Mapped to: usp_ListOrders (confidence: 100%, exact match: usp_ListOrders)
func (r *OrderServiceRepositorySQL) ListOrders(ctx context.Context, req *ListOrdersRequest) (*ListOrdersResponse, error) {
	// Execute stored procedure and scan results
	query := "EXEC usp_ListOrders @UserId, @Status, @FromDate, @ToDate"
	row := r.db.QueryRowContext(ctx, query, req.UserID, req.Status, req.FromDate, req.ToDate)
	var result ListOrdersResponse
	err := row.Scan()
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("ListOrders: not found")
		}
		return nil, fmt.Errorf("ListOrders: %w", err)
	}
	
	return &result, nil
}


// UpdateOrderStatus implements the UpdateOrderStatus operation.
// Mapped to: usp_UpdateOrderStatus (confidence: 100%, exact match: usp_UpdateOrderStatus)
func (r *OrderServiceRepositorySQL) UpdateOrderStatus(ctx context.Context, req *UpdateOrderStatusRequest) (*UpdateOrderStatusResponse, error) {
	// Execute stored procedure and scan results
	query := "EXEC usp_UpdateOrderStatus @OrderId, @Status, @TrackingNumber, @Carrier, @Notes"
	row := r.db.QueryRowContext(ctx, query, req.ID, req.Status, req.TrackingNumber, req.Carrier, req.Notes)
	var nested Order
	err := row.Scan()
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("UpdateOrderStatus: not found")
		}
		return nil, fmt.Errorf("UpdateOrderStatus: %w", err)
	}
	
	return &UpdateOrderStatusResponse{
		Order: &nested,
	}, nil
}


// CancelOrder implements the CancelOrder operation.
// Mapped to: usp_CancelOrder (confidence: 100%, exact match: usp_CancelOrder)
func (r *OrderServiceRepositorySQL) CancelOrder(ctx context.Context, req *CancelOrderRequest) (*CancelOrderResponse, error) {
	// Execute stored procedure and scan results
	query := "EXEC usp_CancelOrder @OrderId, @Reason"
	row := r.db.QueryRowContext(ctx, query, req.ID, req.Reason)
	var result CancelOrderResponse
	err := row.Scan(&result.RefundInitiated)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("CancelOrder: not found")
		}
		return nil, fmt.Errorf("CancelOrder: %w", err)
	}
	
	return &result, nil
}


// ProcessPayment implements the ProcessPayment operation.
// Mapped to: usp_ProcessPayment (confidence: 83%, exact match: usp_ProcessPayment)
func (r *OrderServiceRepositorySQL) ProcessPayment(ctx context.Context, req *ProcessPaymentRequest) (*ProcessPaymentResponse, error) {
	// Execute stored procedure (no result mapping)
	query := "EXEC usp_ProcessPayment @OrderId, @PaymentIntentId, @Success"
	_, err := r.db.ExecContext(ctx, query, req.OrderID, req.PaymentIntentID, nil)
	if err != nil {
		return nil, fmt.Errorf("ProcessPayment: %w", err)
	}
	
	return &ProcessPaymentResponse{}, nil
}


// RefundOrder implements the RefundOrder operation.
// Mapped to: usp_RefundOrder (confidence: 75%, exact match: usp_RefundOrder)
func (r *OrderServiceRepositorySQL) RefundOrder(ctx context.Context, req *RefundOrderRequest) (*RefundOrderResponse, error) {
	// Execute stored procedure and scan results
	query := "EXEC usp_RefundOrder @OrderId, @AmountUnits, @Reason, @RefundedBy"
	row := r.db.QueryRowContext(ctx, query, req.OrderID, nil, req.Reason, nil)
	var result RefundOrderResponse
	err := row.Scan(&result.Success, &result.RefundID)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("RefundOrder: not found")
		}
		return nil, fmt.Errorf("RefundOrder: %w", err)
	}
	
	return &result, nil
}


// ValidateDiscountCode implements the ValidateDiscountCode operation.
// Mapped to: usp_ValidateDiscountCode (confidence: 83%, exact match: usp_ValidateDiscountCode)
func (r *OrderServiceRepositorySQL) ValidateDiscountCode(ctx context.Context, req *ValidateDiscountCodeRequest) (*ValidateDiscountCodeResponse, error) {
	// Execute stored procedure and scan results
	query := "EXEC usp_ValidateDiscountCode @Code, @UserId, @CartSubtotalUnits"
	row := r.db.QueryRowContext(ctx, query, req.Code, req.UserID, nil)
	var result ValidateDiscountCodeResponse
	err := row.Scan(&result.IsValid, &result.ErrorMessage, &result.DiscountType)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("ValidateDiscountCode: not found")
		}
		return nil, fmt.Errorf("ValidateDiscountCode: %w", err)
	}
	
	return &result, nil
}


// ============================================================================
// OrderService Server
// ============================================================================

// OrderServiceServer implements the OrderService gRPC service.
type OrderServiceServer struct {
	repo OrderServiceRepository
}

// NewOrderServiceServer creates a new server.
func NewOrderServiceServer(repo OrderServiceRepository) *OrderServiceServer {
	return &OrderServiceServer{repo: repo}
}


// CreateOrder handles the CreateOrder RPC.
func (s *OrderServiceServer) CreateOrder(ctx context.Context, req *CreateOrderRequest) (*CreateOrderResponse, error) {
	return s.repo.CreateOrder(ctx, req)
}

// GetOrder handles the GetOrder RPC.
func (s *OrderServiceServer) GetOrder(ctx context.Context, req *GetOrderRequest) (*GetOrderResponse, error) {
	return s.repo.GetOrder(ctx, req)
}

// GetOrderByNumber handles the GetOrderByNumber RPC.
func (s *OrderServiceServer) GetOrderByNumber(ctx context.Context, req *GetOrderByNumberRequest) (*GetOrderByNumberResponse, error) {
	return s.repo.GetOrderByNumber(ctx, req)
}

// ListOrders handles the ListOrders RPC.
func (s *OrderServiceServer) ListOrders(ctx context.Context, req *ListOrdersRequest) (*ListOrdersResponse, error) {
	return s.repo.ListOrders(ctx, req)
}

// UpdateOrderStatus handles the UpdateOrderStatus RPC.
func (s *OrderServiceServer) UpdateOrderStatus(ctx context.Context, req *UpdateOrderStatusRequest) (*UpdateOrderStatusResponse, error) {
	return s.repo.UpdateOrderStatus(ctx, req)
}

// CancelOrder handles the CancelOrder RPC.
func (s *OrderServiceServer) CancelOrder(ctx context.Context, req *CancelOrderRequest) (*CancelOrderResponse, error) {
	return s.repo.CancelOrder(ctx, req)
}

// ProcessPayment handles the ProcessPayment RPC.
func (s *OrderServiceServer) ProcessPayment(ctx context.Context, req *ProcessPaymentRequest) (*ProcessPaymentResponse, error) {
	return s.repo.ProcessPayment(ctx, req)
}

// RefundOrder handles the RefundOrder RPC.
func (s *OrderServiceServer) RefundOrder(ctx context.Context, req *RefundOrderRequest) (*RefundOrderResponse, error) {
	return s.repo.RefundOrder(ctx, req)
}

// ValidateDiscountCode handles the ValidateDiscountCode RPC.
func (s *OrderServiceServer) ValidateDiscountCode(ctx context.Context, req *ValidateDiscountCodeRequest) (*ValidateDiscountCodeResponse, error) {
	return s.repo.ValidateDiscountCode(ctx, req)
}

