// Code generated by tgpiler. DO NOT EDIT.
// Source: proto definitions + stored procedures

package Review

import (
	"context"
	"database/sql"
	"fmt"
)

// ============================================================================
// ReviewService Repository Implementation
// ============================================================================

// ReviewServiceRepository defines the data access interface for ReviewService.
type ReviewServiceRepository interface {
	CreateReview(ctx context.Context, req *CreateReviewRequest) (*CreateReviewResponse, error)
	GetReview(ctx context.Context, req *GetReviewRequest) (*GetReviewResponse, error)
	ListReviews(ctx context.Context, req *ListReviewsRequest) (*ListReviewsResponse, error)
	ListUserReviews(ctx context.Context, req *ListUserReviewsRequest) (*ListUserReviewsResponse, error)
	UpdateReview(ctx context.Context, req *UpdateReviewRequest) (*UpdateReviewResponse, error)
	DeleteReview(ctx context.Context, req *DeleteReviewRequest) (*DeleteReviewResponse, error)
	VoteReview(ctx context.Context, req *VoteReviewRequest) (*VoteReviewResponse, error)
	GetProductRatingSummary(ctx context.Context, req *GetProductRatingSummaryRequest) (*GetProductRatingSummaryResponse, error)
	ModerateReview(ctx context.Context, req *ModerateReviewRequest) (*ModerateReviewResponse, error)
	ListPendingReviews(ctx context.Context, req *ListPendingReviewsRequest) (*ListPendingReviewsResponse, error)
}

// ReviewServiceRepositorySQL implements ReviewServiceRepository using stored procedures.
type ReviewServiceRepositorySQL struct {
	db *sql.DB
}

// NewReviewServiceRepositorySQL creates a new SQL repository.
func NewReviewServiceRepositorySQL(db *sql.DB) *ReviewServiceRepositorySQL {
	return &ReviewServiceRepositorySQL{db: db}
}


// CreateReview implements the CreateReview operation.
// Mapped to: usp_CreateReview (confidence: 100%, exact match: usp_CreateReview)
func (r *ReviewServiceRepositorySQL) CreateReview(ctx context.Context, req *CreateReviewRequest) (*CreateReviewResponse, error) {
	// Execute stored procedure and scan results
	query := "EXEC usp_CreateReview @ProductId, @UserId, @Rating, @Title, @Content"
	row := r.db.QueryRowContext(ctx, query, req.ProductID, req.UserID, req.Rating, req.Title, req.Content)
	
	var result CreateReviewResponse
	err := row.Scan()
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("CreateReview: not found")
		}
		return nil, fmt.Errorf("CreateReview: %w", err)
	}
	
	return &CreateReviewResponse{
	}, nil
}


// GetReview implements the GetReview operation.
// Mapped to: usp_GetReviewById (confidence: 95%, get by id pattern)
func (r *ReviewServiceRepositorySQL) GetReview(ctx context.Context, req *GetReviewRequest) (*GetReviewResponse, error) {
	// Execute stored procedure and scan results
	query := "EXEC usp_GetReviewById @ReviewId"
	row := r.db.QueryRowContext(ctx, query, req.ID)
	
	var result ReviewResponse
	err := row.Scan()
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("GetReview: not found")
		}
		return nil, fmt.Errorf("GetReview: %w", err)
	}
	
	return &GetReviewResponse{
		ReviewResponse: &result,
	}, nil
}


// ListReviews implements the ListReviews operation.
// Mapped to: usp_ListReviews (confidence: 100%, exact match: usp_ListReviews)
func (r *ReviewServiceRepositorySQL) ListReviews(ctx context.Context, req *ListReviewsRequest) (*ListReviewsResponse, error) {
	// Execute stored procedure and scan results
	query := "EXEC usp_ListReviews @ProductId, @MinRating, @MaxRating, @VerifiedOnly, @SortBy, @SortDescending"
	row := r.db.QueryRowContext(ctx, query, req.ProductID, req.MinRating, req.MaxRating, req.VerifiedOnly, req.SortBy, req.SortDescending)
	
	var result ListReviewsResponse
	err := row.Scan()
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("ListReviews: not found")
		}
		return nil, fmt.Errorf("ListReviews: %w", err)
	}
	
	return &ListReviewsResponse{
	}, nil
}


// ListUserReviews implements the ListUserReviews operation.
// Mapped to: usp_ListUserReviews (confidence: 100%, exact match: usp_ListUserReviews)
func (r *ReviewServiceRepositorySQL) ListUserReviews(ctx context.Context, req *ListUserReviewsRequest) (*ListUserReviewsResponse, error) {
	// Execute stored procedure and scan results
	query := "EXEC usp_ListUserReviews @UserId"
	row := r.db.QueryRowContext(ctx, query, req.UserID)
	
	var result ListUserReviewsResponse
	err := row.Scan()
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("ListUserReviews: not found")
		}
		return nil, fmt.Errorf("ListUserReviews: %w", err)
	}
	
	return &ListUserReviewsResponse{
	}, nil
}


// UpdateReview implements the UpdateReview operation.
// Mapped to: usp_UpdateReview (confidence: 100%, exact match: usp_UpdateReview)
func (r *ReviewServiceRepositorySQL) UpdateReview(ctx context.Context, req *UpdateReviewRequest) (*UpdateReviewResponse, error) {
	// Execute stored procedure and scan results
	query := "EXEC usp_UpdateReview @ReviewId, @UserId, @Rating, @Title, @Content"
	row := r.db.QueryRowContext(ctx, query, req.ID, req.UserID, req.Rating, req.Title, req.Content)
	
	var result UpdateReviewResponse
	err := row.Scan()
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("UpdateReview: not found")
		}
		return nil, fmt.Errorf("UpdateReview: %w", err)
	}
	
	return &UpdateReviewResponse{
	}, nil
}


// DeleteReview implements the DeleteReview operation.
// Mapped to: usp_DeleteReview (confidence: 100%, exact match: usp_DeleteReview)
func (r *ReviewServiceRepositorySQL) DeleteReview(ctx context.Context, req *DeleteReviewRequest) (*DeleteReviewResponse, error) {
	// Execute stored procedure (no result mapping)
	query := "EXEC usp_DeleteReview @ReviewId, @UserId"
	_, err := r.db.ExecContext(ctx, query, req.ID, req.UserID)
	if err != nil {
		return nil, fmt.Errorf("DeleteReview: %w", err)
	}
	
	return &DeleteReviewResponse{}, nil
}


// VoteReview implements the VoteReview operation.
// Mapped to: usp_VoteReview (confidence: 100%, exact match: usp_VoteReview)
func (r *ReviewServiceRepositorySQL) VoteReview(ctx context.Context, req *VoteReviewRequest) (*VoteReviewResponse, error) {
	// Execute stored procedure and scan results
	query := "EXEC usp_VoteReview @ReviewId, @UserId, @Helpful"
	row := r.db.QueryRowContext(ctx, query, req.ReviewID, req.UserID, req.Helpful)
	
	var result VoteReviewResponse
	err := row.Scan(&result.HelpfulVotes, &result.UnhelpfulVotes)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("VoteReview: not found")
		}
		return nil, fmt.Errorf("VoteReview: %w", err)
	}
	
	return &VoteReviewResponse{
	}, nil
}


// GetProductRatingSummary implements the GetProductRatingSummary operation.
// Mapped to: usp_GetProductRatingSummary (confidence: 100%, exact match: usp_GetProductRatingSummary)
func (r *ReviewServiceRepositorySQL) GetProductRatingSummary(ctx context.Context, req *GetProductRatingSummaryRequest) (*GetProductRatingSummaryResponse, error) {
	// Execute stored procedure (no result mapping)
	query := "EXEC usp_GetProductRatingSummary @ProductId"
	_, err := r.db.ExecContext(ctx, query, req.ProductID)
	if err != nil {
		return nil, fmt.Errorf("GetProductRatingSummary: %w", err)
	}
	
	return &GetProductRatingSummaryResponse{}, nil
}


// ModerateReview implements the ModerateReview operation.
// Mapped to: usp_ModerateReview (confidence: 100%, exact match: usp_ModerateReview)
func (r *ReviewServiceRepositorySQL) ModerateReview(ctx context.Context, req *ModerateReviewRequest) (*ModerateReviewResponse, error) {
	// Execute stored procedure (no result mapping)
	query := "EXEC usp_ModerateReview @ReviewId, @Status, @RejectionReason, @ModeratedBy"
	_, err := r.db.ExecContext(ctx, query, req.ID, req.Status, req.RejectionReason, req.ModeratedBy)
	if err != nil {
		return nil, fmt.Errorf("ModerateReview: %w", err)
	}
	
	return &ModerateReviewResponse{}, nil
}


// ListPendingReviews implements the ListPendingReviews operation.
// Mapped to: usp_ListPendingReviews (confidence: 75%, exact match: usp_ListPendingReviews)
func (r *ReviewServiceRepositorySQL) ListPendingReviews(ctx context.Context, req *ListPendingReviewsRequest) (*ListPendingReviewsResponse, error) {
	// Execute stored procedure and scan results
	query := "EXEC usp_ListPendingReviews "
	row := r.db.QueryRowContext(ctx, query, )
	
	var result ListPendingReviewsResponse
	err := row.Scan()
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("ListPendingReviews: not found")
		}
		return nil, fmt.Errorf("ListPendingReviews: %w", err)
	}
	
	return &ListPendingReviewsResponse{
	}, nil
}


// ============================================================================
// ReviewService Server
// ============================================================================

// ReviewServiceServer implements the ReviewService gRPC service.
type ReviewServiceServer struct {
	repo ReviewServiceRepository
}

// NewReviewServiceServer creates a new server.
func NewReviewServiceServer(repo ReviewServiceRepository) *ReviewServiceServer {
	return &ReviewServiceServer{repo: repo}
}


// CreateReview handles the CreateReview RPC.
func (s *ReviewServiceServer) CreateReview(ctx context.Context, req *CreateReviewRequest) (*CreateReviewResponse, error) {
	return s.repo.CreateReview(ctx, req)
}

// GetReview handles the GetReview RPC.
func (s *ReviewServiceServer) GetReview(ctx context.Context, req *GetReviewRequest) (*GetReviewResponse, error) {
	return s.repo.GetReview(ctx, req)
}

// ListReviews handles the ListReviews RPC.
func (s *ReviewServiceServer) ListReviews(ctx context.Context, req *ListReviewsRequest) (*ListReviewsResponse, error) {
	return s.repo.ListReviews(ctx, req)
}

// ListUserReviews handles the ListUserReviews RPC.
func (s *ReviewServiceServer) ListUserReviews(ctx context.Context, req *ListUserReviewsRequest) (*ListUserReviewsResponse, error) {
	return s.repo.ListUserReviews(ctx, req)
}

// UpdateReview handles the UpdateReview RPC.
func (s *ReviewServiceServer) UpdateReview(ctx context.Context, req *UpdateReviewRequest) (*UpdateReviewResponse, error) {
	return s.repo.UpdateReview(ctx, req)
}

// DeleteReview handles the DeleteReview RPC.
func (s *ReviewServiceServer) DeleteReview(ctx context.Context, req *DeleteReviewRequest) (*DeleteReviewResponse, error) {
	return s.repo.DeleteReview(ctx, req)
}

// VoteReview handles the VoteReview RPC.
func (s *ReviewServiceServer) VoteReview(ctx context.Context, req *VoteReviewRequest) (*VoteReviewResponse, error) {
	return s.repo.VoteReview(ctx, req)
}

// GetProductRatingSummary handles the GetProductRatingSummary RPC.
func (s *ReviewServiceServer) GetProductRatingSummary(ctx context.Context, req *GetProductRatingSummaryRequest) (*GetProductRatingSummaryResponse, error) {
	return s.repo.GetProductRatingSummary(ctx, req)
}

// ModerateReview handles the ModerateReview RPC.
func (s *ReviewServiceServer) ModerateReview(ctx context.Context, req *ModerateReviewRequest) (*ModerateReviewResponse, error) {
	return s.repo.ModerateReview(ctx, req)
}

// ListPendingReviews handles the ListPendingReviews RPC.
func (s *ReviewServiceServer) ListPendingReviews(ctx context.Context, req *ListPendingReviewsRequest) (*ListPendingReviewsResponse, error) {
	return s.repo.ListPendingReviews(ctx, req)
}

